### ISSUE TITLE
Some question about ResolvePackageNotFound

### ISSUE THREAD

**Issue by NJU-Bio-Info** [YangLab/SCAPTURE#4]
Hello, such an amazing tool for APA prediction! When I try to create an environment for SCATURE via using command
`conda env create -f SCAPTURE_env.yaml`, I met an error described as follow: 
ResolvePackageNotFound:
  - bedtools==2.26.0=hc088bd4_0
  - umi_tools==1.1.1=py37hf01694f_0

So, I checked my bedtools and found its version is 2.29.1, you mean I should install bedtools (2.26.0) instead of bedtools (2.29.1)?
As for the umi_tools, I have searched it on bioconda and found that this version (1.1.1) has been labelled with broken. So I'm trying to ask some applicable advice to solve such problems. 
Sincere thanks to you!

**Comment by liguowei-CAS** [comment]
The version of umi_tools is not sensitive.
`conda install -c bioconda umi_tools -n SCAPTURE_env`

But, some latest versions of bedtools might get different outcomes, we still recommend using 2.26.0 (it could be found in biobuilds channel currently).
`conda install -c biobuilds bedtools -n SCAPTURE_env`
